DROP TABLE transactions IF EXISTS;

CREATE TABLE transactions  (
    id DOUBLE PRECISION IDENTITY NOT NULL PRIMARY KEY,
    buyer VARCHAR NOT NULL,
    store VARCHAR NOT NULL,
    item VARCHAR NOT NULL,
    price DOUBLE PRECISION NOT NULL,
);
